config/routes.rb
Rails.application.routes.draw do

  resources :teams
  resources :fantasy_teams
  resources :fantasy_players, only: [:edit, :update]
  resources :fantasy_projections, only: [:show]
  root 'welcome#index'
  get 'players', to: 'players#index'
  get '/hello_world', to: 'welcome#hello_world'
  get '/load_draft_rankings', to: 'welcome#load_draft_rankings'
  get '/load_fantasy_players', to: 'welcome#load_fantasy_players'
  get '/load_fantasy_projections', to: 'welcome#load_fantasy_projections'
  get '/load_auction', to: 'welcome#load_auction'
  get '/code_red', to: 'welcome#code_red'
  
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    
  end
  
  def hello_world
    puts "asdjfalsdjflasjfdsl"
  end
  
  def load_draft_rankings
    # execute first
    Player.InitialDraftRankings  
  end
  
  def load_fantasy_players
    # execute second
    FantasyPlayer.InsertPlayers  
  end
  
  def load_fantasy_projections
    # execute third
    FantasyProjection.QB_InitialProjections  
    FantasyProjection.RB_InitialProjections
    FantasyProjection.WR_InitialProjections  
    FantasyProjection.TE_InitialProjections
    FantasyProjection.DEF_InitialProjections  
    FantasyProjection.K_InitialProjections
  end
  
  def load_auction
    # execute fourth
    Auction.InitialAuction
    Auction.UpdateProjectedPrice
  end
  
  def code_red
    # destroys everything
    Player.destroy_all
    FantasyPlayer.destroy_all
    FantasyProjection.destroy_all
    Auction.destroy_all
  end
  
end

app/views/welcome/index.html.erb
<h1>
  Welcome
</h1>

<%= link_to 'Test', hello_world_path, method: :get %><br>
<%= link_to 'Load Draft Rankings', load_draft_rankings_path, method: :get %><br>
<%= link_to 'Load Fantasy Players', load_fantasy_players_path, method: :get %><br>
<%= link_to 'Load Fantasy Projections', load_fantasy_projections_path, method: :get %><br>
<%= link_to 'Load Auction', load_auction_path, method: :get %><br><br><br><br>
<%= link_to 'Code Red', code_red_path, method: :get %>