config/routes.rb
Rails.application.routes.draw do

  resources :teams
  resources :fantasy_teams
  resources :fantasy_players, only: [:edit, :update]
  resources :fantasy_projections, only: [:show]
  root 'welcome#index'
  get 'players', to: 'players#index'
  get '/hello_world', to: 'welcome#hello_world'
  get '/load_draft_rankings', to: 'welcome#load_draft_rankings'
  get '/load_fantasy_players', to: 'welcome#load_fantasy_players'
  get '/load_fantasy_projections', to: 'welcome#load_fantasy_projections'
  get '/load_auction', to: 'welcome#load_auction'
  get '/code_red', to: 'welcome#code_red'
  
  
end

app/models/fantasy_team.rb
class FantasyTeam < ApplicationRecord
  
  has_many :fantasy_players
  
  def self.position_count(fantasy_team_id)
    players = FantasyPlayer.joins(:player).select("players.position as posti").where(fantasy_team_id: fantasy_team_id).map(&:posti)

    position_hash = Hash.new(0)

    players.each do |v|
      position_hash [v] += 1
    end

    position_hash.each do |k, v|
      puts "#{k}: #{v}"
    end    
  end
  
end

app/controllers/fantasy_teams_controller.rb
class FantasyTeamsController < ApplicationController
  
  def index
    @fantasyTeams = FantasyTeam.all
  end
  
  def new
    @fantasyTeam = FantasyTeam.new
  end
  
  def create 
    @fantasyTeam = FantasyTeam.new(ft_params)
    if @fantasyTeam.save
      flash[:success] = "Team was created"
      redirect_to fantasy_teams_path
    else
      render 'new'
    end
  end
  
  def edit
    @fantasyTeam = FantasyTeam.find(params[:id])
  end
  
  def update
    @fantasyTeam = FantasyTeam.find(params[:id])
    if @fantasyTeam.update(ft_params)
      flash[:notice] = "Updated"
      redirect_to fantasy_teams_path
    else
      render 'edit'
    end
  end
  
  def show
    @fantasyTeam = FantasyTeam.find(params[:id])
    @players = FantasyPlayer.joins(:player).where(fantasy_team_id: @fantasyTeam)
  end
  
  private
  
  def ft_params
    params.require(:fantasy_team).permit(:fantasy_team_name, :owner_name, :auction_cash)
  end
  
end

app/views/fantasy_teams/_form.html.erb
<%= form_for(@fantasyTeam, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<br>
<%= f.label :fantasy_team_name %>
<%= f.text_field :fantasy_team_name, class: "form-control", autofocus: true %>
<br>
<%= f.label :owner_name %>
<%= f.text_field :owner_name, class: "form-control" %>
<br>
<%= f.label :auction_cash %>
<%= f.text_field :auction_cash, class: "form-control" %>
<br>
<%= f.submit %>

<% end %>

app/views/fantasy_teams/edit.html.erb
<h1>
  Edit <%= @fantasyTeam.fantasy_team_name %>
</h1>
  
<%= render 'form' %>

app/views/fantasy_teams/index.html.erb
<h1 align = "center">
  Fantasy Teams
</h1>
<br>
<table>
<%= link_to "Create Fantasy Team", new_fantasy_team_path %>
  <tr>
    <th>Team Name</th>
    <th>Team Owner</th>
    <th>Auction Cash</th>
    <th>Nerd Rank Sum</th>
  </tr>
  <% @fantasyTeams.each do |fantasyTeams| %>
  <tr>
    <td><%= fantasyTeams.fantasy_team_name %></td>
    <td><%= fantasyTeams.owner_name %></td>
    <td><%= number_to_currency(fantasyTeams.auction_cash) %></td>
    <td><%= FantasyPlayer.calculateNerdRank(fantasyTeams).to_i %></td>
  </tr>
<% end %>
</table>

app/views/fantasy_teams/new.html.erb
<h1>
  New Fantasy Team
</h1>

<%= render 'form' %>

app/views/fantasy_teams/show.html.erb
<h1>
  Team <%= @fantasyTeam.fantasy_team_name %>
</h1>
<h2>
  <% spentCash = FantasyPlayer.calculateAuctionCash(@fantasyTeam) %>
  <% auctionCash = @fantasyTeam.auction_cash %>
 Auction Cash <%= number_to_currency(auctionCash) %><br>
 Remaining Cash <%= number_to_currency(auctionCash - spentCash) %>
</h2>

<h2>
  Player Count: <%= @players.count %><br>
  <%= FantasyTeam.position_count(@fantasyTeam) %>
</h2>
<h4>
  Players:
</h4>
<% @players.each do |player| %>
  <ul>
    <li><%= player.player.display_name %>, <%= player.player.position %></li>
  </ul>
<% end %>
<%= link_to "Back", players_path %>