config/routes.rb
Rails.application.routes.draw do

  resources :teams
  resources :fantasy_teams
  resources :fantasy_players, only: [:edit, :update]
  resources :fantasy_projections, only: [:show]
  root 'welcome#index'
  get 'players', to: 'players#index'
  get '/hello_world', to: 'welcome#hello_world'
  get '/load_draft_rankings', to: 'welcome#load_draft_rankings'
  get '/load_fantasy_players', to: 'welcome#load_fantasy_players'
  get '/load_fantasy_projections', to: 'welcome#load_fantasy_projections'
  get '/load_auction', to: 'welcome#load_auction'
  get '/code_red', to: 'welcome#code_red'
  
  
end

app/models/player.rb
class Player < ApplicationRecord
  self.primary_key = :id
  
  has_one :fantasy_player
  has_one :fantasy_projection
  has_one :auction
  has_one :fantasy_team, through: :fantasy_player
    
  filterrific(
   default_filter_params: { sorted_by: 'nerd_rank_asc' },
   available_filters: [
     :search_query,
     :filter_player_position,
     :filter_fantasy_team,
     :filter_watching,
     :filter_rookie_asset,
     :sorted_by
   ]
 )

  scope :filter_player_position, lambda { |position|
    where(position: [*position])
  }
  
  scope :filter_fantasy_team, lambda { |team|
    where(fantasy_teams: { fantasy_team_name: team }).joins(:fantasy_team)
  }
  
  scope :filter_watching, lambda { |watching|
    where(fantasy_players: { watch: watching }).joins(:fantasy_player)
  }

  scope :filter_rookie_asset, lambda { |rookieAsset|
    where(fantasy_players: { rookie_asset: rookieAsset }).joins(:fantasy_player)
  }
  
  scope :search_query, lambda { |query|
  return nil  if query.blank?
  # condition query, parse into individual keywords
  terms = query.downcase.split(/\s+/)
  terms = terms.map { |e|
    (e.gsub('*', '%') + '%').gsub(/%+/, '%')
  }
  num_or_conds = 2
  where(
    terms.map { |term|
      "(LOWER(players.first_name) LIKE ? OR LOWER(players.last_name) LIKE ?)"
    }.join(' AND '),
    *terms.map { |e| [e] * num_or_conds }.flatten
  )
  }
  
  scope :sorted_by, lambda { |sort_option|
  # extract the sort direction from the param value.
  direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
  case sort_option.to_s
  when /^overall_rank_/
    order("players.overall_rank #{ direction }")
  when /^nerd_rank_/
    order("players.nerd_rank #{ direction }")
  when /^position_rank_/
    order("players.position_rank #{ direction }")
  when /^projected_price_/
    order("fantasy_players.auction_projected_price #{ direction }").includes(:fantasy_player).references(:fantasy_player)        
  when /^spend_price_/
    order("fantasy_players.auction_spend_price #{ direction }").includes(:fantasy_player).references(:fantasy_player)
  when /^sold_price_/
    order("fantasy_players.auction_sold_price #{ direction }").includes(:fantasy_player).references(:fantasy_player)

  else
    raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
  end
}
  
  def self.options_for_select
    Player.select(:position).distinct.map(&:position)
  end
  
  def self.options_for_fantasy_team
    FantasyTeam.select(:fantasy_team_name).distinct.map(&:fantasy_team_name)
  end
  
  def self.options_for_watch
    FantasyPlayer.select(:watch).distinct.map(&:watch)
  end
  
  def self.options_for_rookie_asset
    FantasyPlayer.select(:rookie_asset).distinct.map(&:rookie_asset)
  end
  
  def self.options_for_sorted_by
    [
      ['Nerd Rank', 'nerd_rank_asc'],
      ['Overall Rank', 'overall_rank_asc'],
      ['Position Rank', 'position_rank_asc'],
      ['Projected Price (High)', 'projected_price_desc'],
      ['Projected Price (Low)', 'projected_price_asc'],
      ['Spend Price (High)', 'spend_price_desc'],
      ['Spend Price (Low)', 'spend_price_asc'],
      ['Sold Price (High)', 'sold_price_desc'],
      ['Sold Price (Low)', 'sold_price_asc']
    ]
  end
  
#####################################################
  # Load Script
#####################################################
  
  def self.InitialDraftRankings
    players = HTTParty.get("https://www.fantasyfootballnerd.com/service/draft-rankings/json/#{ENV["API_FOOTBALL"]}/1/")

    playerSize = players["DraftRankings"].size
    arrayPosition = 0

    until playerSize == 0
      
      player = players["DraftRankings"][arrayPosition]
      
      playerId = player["playerId"]
      playerPosition = player["position"]
      displayName = player["displayName"]
      firstName = player["fname"]
      lastName = player["lname"]
      team = player["team"]
      byeWeek = player["byeWeek"]
      nerdRank = player["nerdRank"]
      positionRank = player["positionRank"]
      overallRank = player["overallRank"]
      
      Player.create(id: "#{playerId}", position: "#{playerPosition}", display_name: "#{displayName}", 
                    first_name: "#{firstName}", last_name: "#{lastName}", team: "#{team}",
                    bye_week: "#{byeWeek}", nerd_rank: "#{nerdRank}", position_rank: "#{positionRank}",
                    overall_rank: "#{overallRank}")
      playerSize -= 1
      arrayPosition += 1
    end

  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  
  def index
    @fantasy_teams = FantasyTeam.all
 @filterrific = initialize_filterrific(
      Player,
      params[:filterrific],
      select_options: {
        sorted_by: Player.options_for_sorted_by,
        filter_player_position: Player.options_for_select,
        filter_fantasy_team: Player.options_for_fantasy_team,
        filter_watching: Player.options_for_watch,
        filter_rookie_asset: Player.options_for_rookie_asset
      },
      persistence_id: 'shared_key',
      default_filter_params: {},
      available_filters: [:search_query, :filter_player_position, :filter_fantasy_team, :filter_watching, :filter_rookie_asset, :sorted_by],
      sanitize_params: true
    ) or return

    #@players = @filterrific.find.page(params[:page])
    @fantasy_players = @filterrific.find.page(params[:page])

    # Respond to html for initial page load and to js for AJAX filter updates.
    respond_to do |format|
      format.html
      format.js
    end


  rescue ActiveRecord::RecordNotFound => e
    # There is an issue with the persisted param_set. Reset it.
    puts "Had to reset filterrific params: #{ e.message }"
    redirect_to(reset_filterrific_url(format: :html)) and return
  

  end
end

app/views/players/_list.html.erb
<div id="filterrific_results">

  <div>
    <%= page_entries_info @fantasy_players %>
  </div>
<table class="table table-striped table-bordered table-hover table">
  <thead>
    <tr>
      <th>Fullname</th>
      <th>Position</th>
      <th>Team</th>
      <th>Nerd Rank</th>
      <th>Overall Rank</th>
      <th>Position Rank</th>
      <th>Fantasy Team</th>
      <th>Watching</th>
      <th>Keeper</th>
      <th>Rookie Asset</th>
      <th>Projected Price</th>
      <th>Spend Price</th>
      <th>Sold Price</th>
    </tr>
  </thead>
  <tbody>
    <% @fantasy_players.each do |player| %>
      <tr>
        <td><%= link_to player.display_name, fantasy_projection_path(player.id) %></td>
        <td><%= player.position %></td>
        <td><%= player.team %></td>
        <td><%= player.nerd_rank %></td>
        <td><%= player.overall_rank %></td>
        <td><%= player.position_rank %></td>
        <td><%= player.fantasy_team.fantasy_team_name %></td>
        <td><%= player.fantasy_player.watch %></td>
        <td><%= player.fantasy_player.keeper %></td>
        <td><%= player.fantasy_player.rookie_asset %></td>
        <% projected_price = player.fantasy_player.auction_projected_price.to_f * 10 %>
        <td><%= number_to_currency(projected_price) %></td>
        <td><%= number_to_currency(player.fantasy_player.auction_spend_price) %></td>
        <td><%= number_to_currency(player.fantasy_player.auction_sold_price) %></td>
        <td><%= link_to "Edit", edit_fantasy_player_path(player) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  <%= will_paginate @fantasy_players %>
</div>

app/views/players/index.html.erb
<h1>Teams</h1>
<% @fantasy_teams.each do |team| %>
  <text><%= link_to team.fantasy_team_name, fantasy_team_path(team.id) %>
    <% auctionCash = team.auction_cash %>
    <% spentCash = FantasyPlayer.calculateAuctionCash(team) %>
    <%= number_to_currency(auctionCash - spentCash) %> ||</text>
<% end %>

<h1>Players</h1>

<%= form_for_filterrific @filterrific, html: { id: 'filterrific-no-ajax-auto-submit' } do |f| %>
<div>
    Search
    <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
    <%= f.text_field(
      :search_query
    ) %>
  </div>  
<div>
    Position
    <%= f.select(
      :filter_player_position,
      @filterrific.select_options[:filter_player_position],
      { include_blank: '- All -' }
    ) %>
</div>
<div>
    Fantasy Team
    <%= f.select(
      :filter_fantasy_team,
      @filterrific.select_options[:filter_fantasy_team],
      { include_blank: '- All -' }
    ) %>
</div>
<div>
    Watching
    <%= f.select(
      :filter_watching,
      @filterrific.select_options[:filter_watching],
      { include_blank: '- All -' }
    ) %>
</div>
<div>
    Rookie Asset
    <%= f.select(
      :filter_rookie_asset,
      @filterrific.select_options[:filter_rookie_asset],
      { include_blank: '- All -' }
    ) %>
</div>
<div>
    Sorted by
    <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by]) %>
</div>
  <div>
    <%= link_to(
      'Reset filters',
      reset_filterrific_url,
    ) %>
  </div>
<%= f.submit 'Filter' %>
<% end %>

<%= render(
  partial: 'players/list',
  locals: { players: @players }
) %>

app/views/players/index.js.erb
<%# app/views/students/index.js.erb %>
<% js = escape_javascript(
  render(partial: 'players/list', locals: { players: @fantasy_players })
) %>
$("#filterrific_results").html("<%= js %>");